### ISSUE TITLE
Harden against erroneous data from the wayback machine

### ISSUE THREAD

**Issue by nulldg** [oldcordapp/OldCordV3#30]
sometimes the wayback machine returns an error page but with HTTP 200 as the status, so we'll need to add an extra check to the content itself to make sure it's not a known error page from the wayback machine shitting itself again.

**Comment by ohayo** [comment]
In an ideal world, the oldcordapp cdn should serve everything old discord users can use.

And will be the goto for projects like this. Let's make discord history great again.
