### ISSUE TITLE
Cleanup relationships

### ISSUE THREAD

**Issue by nulldg** [oldcordapp/OldCordV3#59]
- reduce the substantial duplication in relationships.js so it's much easier to maintain
- relationships in the database are far too large, storing entire user objects instead of snowflakes
- when a relationship is cleared, completely delete the relationship rather than setting its state to none
- ideally, relationships should be a table of its own, with the primary key being the userid

the latter 3 points elevate the priority of this issue: storing that much info in a single column could lead to corruption and/or errors if a user has too many friends or blocks.

**Comment by ohayo** [comment]
I'll take a look at this during the weekend. Duplicated code will not be tolerated here on Oldcord.

**Comment by LG125YT** [comment]
Please make no mistakes, its far from complete. Yes, i restructured the table and most of the functions in relation to modifying relationships, but as i have said before, i have yet to rewrite the logic for most of the affected routes.

**Comment by LG125YT** [comment]
After some basic testing, I have determined that is it complete.
