### ISSUE TITLE
Select QoL mods on selector

### ISSUE THREAD

**Issue by nulldg** [oldcordapp/OldCordV3#63]
previously we were considering adding the option to enable/disable QoL patches to the discord client's options, but i realized that's an inappropriate and unintuitive place for it. the patcher is controlled by selector cookies and local storage, so it would be easier to simply put more options there rather than trying to embed them into the discord client.

by including it in the selector instead, we can let the user inject whatever old client mods they want, including our own custom oldcord client mods (such as `user-select` on 2015).

**Comment by Deskehs** [comment]
I think we should force some mods depending on platform as well, like forcing Electron patches if you're running Electron. But yeah I do agree that most QoL patches should be optional.
